In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)


In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [23]:
len(np.linspace(0,7,21))

21

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(1)

array([0.52387248])

In [30]:
np.random.rand(5,2)

array([[0.06227404, 0.26002693],
       [0.29832421, 0.63825181],
       [0.59678603, 0.49017949],
       [0.25244132, 0.32489921],
       [0.15844043, 0.50723213]])

In [31]:
np.random.randn(10)

array([ 1.89932998e+00,  1.34876797e+00,  1.24207065e-01,  1.23088165e-03,
       -1.64637315e-01,  2.11671808e-01, -4.19578153e-01,  2.79654313e-01,
       -2.23003405e+00, -3.57490915e-01])

In [32]:
np.random.randn(2,3)

array([[-0.04980391, -0.73352278, -1.12839238],
       [-0.74998135, -0.07614593,  0.20384932]])

In [34]:
np.random.randint(0,101,(4,5))

array([[10, 35, 56,  7, 85],
       [55, 52,  6, 19, 33],
       [65, 73, 55, 37,  7],
       [65, 90, 64, 73,  8]])

In [36]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [37]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [38]:
arr = np.arange(0,25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [41]:
ranarr = np.random.randint(0,101,10)

In [42]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [43]:
ranarr.max()

92

In [44]:
ranarr.min()

4

In [45]:
ranarr.argmax()

7

In [46]:
ranarr.argmin()

3

In [48]:
ranarr.dtype

dtype('int32')

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr.shape

(25,)

In [51]:
arr = arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

In [54]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])